Tue Dec 01 15:44:27 GMT 2020 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Tue Dec 01 15:44:28 GMT 2020:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0176-1ef9-e84f-000078124131 
on database directory E:\Documents\NetBeansProjects\SmartCare\db\SmartCareDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_171/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_171-b11
user.dir=C:\Program Files\Java\jdk1.8.0_171\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=E:\Documents\NetBeansProjects\SmartCare\db
Database Class Loader started - derby.database.classpath=''
Tue Dec 01 15:44:28 GMT 2020 Thread[DRDAConnThread_2,5,main] (XID = 179), (SESSIONID = 0), (DATABASE = SmartCareDB), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Tue Dec 01 15:44:28 GMT 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = SmartCareDB), (DRDAID = {1}), Connection authentication failure occurred.  Reason: Invalid authentication..
----------------------------------------------------------------
Tue Dec 01 15:45:27 GMT 2020:
Shutting down instance a816c00e-0176-1ef9-e84f-000078124131 on database directory E:\Documents\NetBeansProjects\SmartCare\db\SmartCareDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Tue Dec 01 15:45:27 GMT 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = SmartCareDB), (DRDAID = {3}), Database 'SmartCareDB' shutdown.
----------------------------------------------------------------
Tue Dec 01 15:45:50 GMT 2020:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 20e1c02b-0176-1ef9-e84f-000078124131 
on database directory E:\Documents\NetBeansProjects\SmartCare\db\SmartCareDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_171/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_171-b11
user.dir=C:\Program Files\Java\jdk1.8.0_171\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=E:\Documents\NetBeansProjects\SmartCare\db
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Tue Dec 01 15:45:56 GMT 2020:
Shutting down instance 20e1c02b-0176-1ef9-e84f-000078124131 on database directory E:\Documents\NetBeansProjects\SmartCare\db\SmartCareDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Tue Dec 01 15:45:56 GMT 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = SmartCareDB), (DRDAID = {5}), Database 'SmartCareDB' shutdown.
----------------------------------------------------------------
Tue Dec 01 16:01:01 GMT 2020:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 13a100c9-0176-1ef9-e84f-000078124131 
on database directory E:\Documents\NetBeansProjects\SmartCare\db\SmartCareDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_171/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_171-b11
user.dir=C:\Program Files\Java\jdk1.8.0_171\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=E:\Documents\NetBeansProjects\SmartCare\db
Database Class Loader started - derby.database.classpath=''
